### ISSUE TITLE
OpenCV video capture

### ISSUE THREAD

**Issue by Davidy22** [Davidy22/scholarlySkunkJam#1]

**Comment by garuna-m6** [comment]
@Davidy22 what is the expectation of this issue (acceptance criteria) ?

**Comment by Davidy22** [comment]
A series of images in a format we can process to ASCII, generated at a sufficient rate for video. 30 fps is smooth enough, 20 fps is probably acceptable for text based fidelity, 10 is on the low side, 5 is probably too low.
