### ISSUE TITLE
[FEATURE] Improve Selection of Effects

### ISSUE THREAD

**Issue by GarvitSinghh** [Davidy22/scholarlySkunkJam#90]
**Is your feature request related to a problem? Please describe.**
When you go to the effects panel and select effects like Question-mark, Arrows, etc. Only the effect last selected is applied but the other effects still remain checked.

**Describe the solution you'd like**
When a particular effect overrides other effects, they should be unchecked from the list.

**Comment by Davidy22** [comment]
So, it's the way it is because effects don't necessarily fully overwrite others, and this allows for combining them. Mostly the ones that fully overwrite each other are the ASCII based ones, but even then not necessarily.
